### ISSUE TITLE
DedicatedServer CRD

### ISSUE THREAD

**Issue by frantjc** [frantjc/valheimw#86]
## Dependencies

https://github.com/frantjc/sindri/issues/87

## What does the user want

As a user, I want to be able to click a button and create a new Server instance of a Steamapp for myself.

## Why do we want to support this

Sindri could do this better than anyone doing it on VMs because it will be closer to bare metal hardware and have better resource sharing.

## What should this look like

TODO(frantjc)

```yaml
apiVersion: sindri.frantj.cc/v1alpha1
kind: DedicatedServer
metadata:
  name: my-valheim-server-0
spec:
  steamapp:
    name: 896660-public
```
